version: "3"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  database:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
      DB_NAME: ${DB_NAME}
    build:
      context: ./database
      dockerfile: Dockerfile
      args:
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        PGDATA: /var/lib/postgresql/data
        DB_NAME: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_LOCAL_PORT=5432
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - DB_SCHEMA=${DB_SCHEMA}
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/src:/app/src

volumes:
  db_data:
