version: "3"

services:
  front:
    build:
      context: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/usr/src/frontend/src

  db:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
      DB_NAME: ${DB_NAME}
    build:
      context: ./db
      dockerfile: Dockerfile
      args:
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        PGDATA: /var/lib/postgresql/data
        DB_NAME: ${DB_NAME}
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - "5432:${DB_PORT}"

  back:
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_LOCAL_PORT=${DB_PORT}
    build: ./back
    ports:
      - "5000:5000"
    volumes:
      - ./back/src:/app/src
